project:
  type: book
  output-dir: _book

book:
  title: "GO UNITE! Strategien zur Sammlung und Sichtbarkeit von Forschungsdaten der eigenen Institution"
  author:  
    - name: Dorothea Strecker
      corresponding: true
      email: dorothea.strecker@hu-berlin.ce
      orcid: 0000-0002-9754-3807
      affiliations: 
        - name: Institut für Bibliotheks- und Informationswissenschaft, Humboldt-Universität zu Berlin, Deutschland
    - name: Birte Cordes
      orcid: 0000-0001-5068-5034
      affiliations: 
        - name: Universitätsbibliothek, Universität Kassel, Deutschland
    - name: Anna Daudrich
      orcid: 0000-0002-7663-5630
      affiliations: 
        - name: Universitätsbibliothek, Zürcher Hochschule für Angewandte Wissenschaften, Schweiz
    - name: Jessica Hiller
      orcid: 0009-0000-1619-0070
      affiliations: 
        - name: Universitätsbibliothek, Technische Universität Clausthal, Deutschland
    - name: Isabel Schuster
      orcid: 0009-0009-0780-8006
      affiliations: 
        - name: Universitätsbibliothek, Friedrich-Alexander-Universität Erlangen-Nürnberg, Deutschland
    - name: Martin Spenger
      orcid: 0000-0002-8841-5985
      affiliations: 
        - name: Universitätsbibliothek, Ludwig-Maximilians-Universität München, Deutschland
  date: "10/01/2026"
  chapters:
    - index.qmd
    - part: "Strategien"
      chapters:
      - strategien/1_Einführung.qmd
      - strategien/2_Vorüberlegungen.qmd
      - strategien/3_Durchführung.qmd
      - strategien/4_Verwendung.qmd
      - strategien/5_Vorbereitung.qmd
      - strategien/6_Zusammenfassung.qmd
      - strategien/references.qmd
#    - part: "Notebooks"

bibliography: strategien/references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    number-depth: 3
